project:
  type: website

website:
  favicon: assets/cropped-NS_Favicon_512x512-32x32.png
  title: "Blog"
  navbar:
    left: 
      - license.qmd
      - link-to-code.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Nanostring-Biostats/CosMx-Analysis-Scratch-Space
      - icon: twitter
        href: https://twitter.com/nanostringtech
      - icon: linkedin
        href: https://www.linkedin.com/company/nanostring-technologies/mycompany/
  page-footer:
    center:
      - text: "License"
        href: "license.qmd"
format:
  html:
    theme: 
      - custom.scss




