project:
  type: website

website:
  favicon: assets/logo_Bruker_black.png
  title: "Blog"
  site-url: https://nanostring-biostats.github.io/CosMx-Analysis-Scratch-Space
  description: "NanoString's CosMx Analysis Scratch Space"
  navbar:
    logo: ./assets/logo_Bruker_white.png
    pinned: true
    collapse: true
    left: 
      - license.qmd
      - link-to-code.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Nanostring-Biostats/CosMx-Analysis-Scratch-Space
      - icon: twitter
        href: https://twitter.com/nanostringtech
      - icon: linkedin
        href: https://www.linkedin.com/company/bruker-spatial
      - icon: rss
        href: index.xml
  cookie-consent:
    type: implied
    style: simple
    palette: light
  google-analytics:
    tracking-id: "G-29W4MW0Y2W"
    anonymize-ip: true
  page-footer:
    center:
      - text: "License"
        href: "license.qmd"
format:
  html:
    theme: 
      light: custom.scss
      dark: darkly




