project:
  type: website
  render:
      - "*.qmd"
      - "guides/"
      - "bbtyes/*"
      - "posts/"
      - "!books/"

website:
  favicon: assets/logo_Bruker_black.png
  title: "Blog"
  site-url: https://nanostring-biostats.github.io/CosMx-Analysis-Scratch-Space
  description: "Bruker Spatial Biology's CosMx Analysis Scratch Space"
  navbar:
    logo: ./assets/logo_Bruker_white.png
    pinned: true
    collapse: true
    left: 
      - text: "Topics" 
        href: about.qmd
      - text: "Guides (new!)"
        href: guides/index.qmd
      - text: "Browser Bytes (new!)"
        href: bbytes/index.qmd
    right:
      - text: "Source Code"
        href: link-to-code.qmd
      - icon: github
        href: https://github.com/Nanostring-Biostats/CosMx-Analysis-Scratch-Space
      - icon: linkedin
        href: https://www.linkedin.com/company/bruker-spatial
      - icon: rss
        href: index.xml
  cookie-consent:
    type: implied
    style: simple
    palette: light
  google-analytics:
    tracking-id: "G-29W4MW0Y2W"
    anonymize-ip: true
  page-footer:
    left: "© 2026 Bruker Spatial Biology"
    center:
      - text: "License"
        href: "license.qmd"
      - text: "Cookie Policy"
        href: "cookie_policy.qmd"
format:
  html:
    theme: 
      light: custom.scss
      dark: [darkly, theme-dark.scss]




