lineagegenes <- list(
  Lineage_Epithelial = c("EPCAM","KRT8","KRT18","KRT19","KRT5","KRT14","KRT15","KRT17","KRT20","MUC1","CLDN4"),
  Lineage_Secretory = c("AGR2","SPDEF","XBP1","SCGB1A1","SCGB3A2","MUC2","MUC5AC","MUC5B"),
  Lineage_Ciliated = c("FOXJ1","TPPP3","PIFO","DNAH5","RSPH1"),
  Lineage_Basal_Squamous = c("TP63","KRT5","KRT14","KRT6A","KRT16"),
  Lineage_Endothelial_Blood = c("PECAM1","VWF","KDR","FLT1","CLDN5","ICAM2"),
  Lineage_Endothelial_Lymphatic = c("PROX1","PDPN","LYVE1","FLT4","CCL21"),
  Lineage_Smooth_Muscle = c("ACTA2","MYH11","TAGLN","CNN1","MYLK"),
  Lineage_Pericyte = c("RGS5","PDGFRB","CSPG4","MCAM","NOTCH3","DES"),
  Lineage_Fibroblast = c("COL1A1","COL1A2","COL3A1","COL6A1","COL6A3","DCN","LUM","DPT","PDGFRA","FAP","CXCL12","MMP2","MMP14"),
  Lineage_Adipocyte = c("ADIPOQ","PPARG","LPL","FABP4","PLIN1","LEP"),
  Lineage_Chondrocyte = c("COL2A1","ACAN","SOX9","MATN3"),
  Lineage_Osteoblast = c("BGLAP","ALPL","SP7","RUNX2","IBSP"),
  Lineage_Osteoclast = c("CTSK","ACP5","MMP9","TM7SF4","TNFRSF11A"),
  Lineage_Cardiomyocyte = c("TNNT2","TNNI3","MYH6","MYH7","ACTC1","MYL2","MYL7","PLN","RYR2","GJA1"),
  Lineage_Immune = c("PTPRC","CD74","HLA-DRA","HLA-DRB1"),
  
  Immune_T_NaiveMemory = c("CCR7","IL7R","LTB","SELL","TCF7","LEF1","TRAC"),
  Immune_T_CD8_Effector = c("CD8A","CD8B","GZMB","PRF1","NKGY7"="NKG7","IFNG","CXCR3"),
  Immune_Treg = c("FOXP3","IL2RA","CTLA4","IKZF2","TIGIT"),
  Immune_Tfh = c("CXCR5","BCL6","PDCD1","IL21","ICOS"),
  Immune_NK = c("KLRD1","KLRC1","KLRK1","NKG7","GNLY","PRF1","GZMB","FCGR3A"),
  Immune_B = c("MS4A1","CD79A","CD79B","CD19","BANK1","PAX5","TCL1A"),
  Immune_Plasma = c("MZB1","XBP1","SDC1","PRDM1","JCHAIN","TNFRSF17"),
  Immune_cDC1 = c("CLEC9A","XCR1","IRF8","BATF3","FLT3"),
  Immune_cDC2 = c("FCER1A","CD1C","IRF4","CLEC10A","ITGAX"),
  Immune_pDC = c("CLEC4C","LILRA4","TCF4","IRF7","GZMB"),
  Immune_Monocyte_Classical = c("S100A8","S100A9","S100A12","VCAN","CCR2","LST1"),
  Immune_Monocyte_NonClassical = c("FCGR3A","MS4A7","LILRB2","CX3CR1","ITGAM","HLA-DRA"),
  Immune_Macrophage = c("CD68","CSF1R","MRC1","MARCO","VSIG4","MSR1","CD163","C1QA"),
  Immune_Microglia = c("CX3CR1","P2RY12","P2RY13","TMEM119","TREM2","AIF1"),
  Immune_Neutrophil = c("CSF3R","FCGR3B","CXCR2","S100A8","S100A9","LCN2","MPO","ELANE","AZU1","CTSG"),
  Immune_Eosinophil = c("CCR3","SIGLEC8","PRG2","RNASE2","IL5RA"),
  Immune_Basophil = c("IL3RA","ENPP3","HDC","MS4A2","GATA2"),
  Immune_Mast = c("KIT","TPSAB1","TPSB2","CPA3","HDC","MS4A2","HPGDS"),
  Immune_Erythroid = c("HBB","HBA1","HBA2","ALAS2","GYPA","KLF1"),
  Immune_Megakaryocyte = c("PPBP","PF4","ITGA2B","GP9","GP1BA"),
  
  Neural_Neuron = c("RBFOX3","MAP2","SNAP25","SLC17A7","GAD1","GAD2","TH","CHAT"),
  Neural_Astrocyte = c("GFAP","AQP4","ALDH1L1","SLC1A3","SLC1A2"),
  Neural_Oligodendrocyte = c("MBP","MOG","PLP1","MAG","SOX10"),
  Neural_OPC = c("PDGFRA","CSPG4"),
  Neural_Ependymal = c("FOXJ1","TPPP3","S100B"),
  Neural_ChoroidPlexus = c("TTR","AQP1"),
  
  Liver_Hepatocyte = c("ALB","TTR","APOA1","TF","CYP3A4","CYP2E1","ASGR1"),
  Liver_Cholangiocyte = c("KRT19","KRT7","EPCAM","SPP1","CFTR"),
  Liver_Kupffer = c("VSIG4","MARCO","CLEC4F","CD163"),
  Liver_Stellate = c("RBP1","LRAT","ACTA2","COL1A1","PDGFRB"),
  Liver_LSEC = c("STAB2","CLEC4G","LYVE1","FCGR2B"),
  
  Lung_AT1 = c("AGER","PDPN","CAV1","AQP5"),
  Lung_AT2 = c("SFTPA1","SFTPB","SFTPC","SFTPD","SLC34A2","ABCA3"),
  Lung_Club = c("SCGB1A1","SCGB3A2"),
  Lung_Ionocyte = c("FOXI1","CFTR","ASCL3"),
  Lung_Ciliated = c("FOXJ1","TPPP3","DNAH5","PIFO"),
  Lung_Basal = c("KRT5","KRT15","TP63"),
  Lung_Goblet = c("MUC5AC","SPDEF","TFF3"),
  Lung_Neuroendocrine = c("CHGA","CHGB","ASCL1","CALCA"),
  
  GI_Enterocyte = c("ALDOB","ALPI","FABP1","APOA1","SI"),
  GI_Goblet = c("MUC2","TFF3"),
  GI_Paneth = c("LYZ","DEFA5","DEFA6","REG3A"),
  GI_Enteroendocrine = c("CHGA","CHGB","PCSK1","NEUROD1","PAX6"),
  GI_Tuft = c("POU2F3","TRPM5","DCLK1","IL17RB"),
  GI_Stem = c("LGR5","OLFM4","ASCL2"),
  
  Pancreas_Acinar = c("PRSS1","CPA1","CTRB1","CELA3A"),
  Pancreas_Ductal = c("KRT19","KRT7","SPP1","MUC1","CFTR"),
  Pancreas_Islet_Beta = c("INS","IAPP","PCSK2","PDX1"),
  Pancreas_Islet_Alpha = c("GCG","ARX","MAFB"),
  Pancreas_Islet_Delta = c("SST","HHEX"),
  Pancreas_Islet_PP = c("PPY"),
  Pancreas_Islet_Epsilon = c("GHRL"),
  
  Kidney_Podocyte = c("NPHS1","NPHS2","WT1","PODXL","KIRREL1","SYNPO"),
  Kidney_Mesangial = c("PDGFRB","RGS5","ITGA8","COL4A1","ACTA2"),
  Kidney_ProximalTubule = c("LRP2","CUBN","SLC5A2","SLC34A1","ALDOB","PDZK1"),
  Kidney_TAL = c("SLC12A1","UMOD","KCNJ1","CLDN16"),
  Kidney_DCT = c("SLC12A3","TRPM6","PTH1R","CALB1"),
  Kidney_Collecting_Principal = c("AQP2","AQP3","AQP4","SCNN1A","SCNN1B","SCNN1G"),
  Kidney_Collecting_Intercalated = c("SLC4A1","SLC26A4","ATP6V1B1","FOXI1"),
  Kidney_MaculaDensa = c("NOS1","PTGS2"),
  
  Skin_Keratinocyte_Basal = c("KRT14","KRT5","TP63"),
  Skin_Keratinocyte_Suprabasal = c("KRT1","KRT10","FLG"),
  Skin_Melanocyte = c("TYR","TYRP1","PMEL","MLANA","DCT"),
  Skin_Langerhans = c("CD207","ITGAX"),
  
  Bladder_Urothelium = c("UPK1A","UPK2","UPK3A","KRT20"),
  
  Thyroid_Follicular = c("TG","TPO","SLC5A5","FOXE1"),
  Parathyroid_Chief = c("PTH"),
  Adrenal_Cortex = c("CYP11A1","CYP17A1","HSD3B2","CYP11B1","STAR"),
  Adrenal_Medulla = c("TH","DBH","PNMT","CHGA"),
  Pituitary_Anterior = c("POMC","GH1","PRL","TSHB","LHB","FSHB"),
  
  Ovary_Granulosa = c("FOXL2","FSHR","AMH","CYP19A1"),
  Ovary_Theca = c("CYP17A1","INSL3","STAR"),
  Ovary_Oocyte = c("ZP3","ZP2","GDF9"),
  Uterus_Epithelium = c("PAX8","EPCAM","KRT7","MUC1"),
  Uterus_Stroma = c("IGFBP1","PRL","HOXA10"),
  Testis_Sertoli = c("SOX9","CLDN11","AMH"),
  Testis_Leydig = c("INSL3","CYP17A1","HSD3B1"),
  Testis_Germ = c("DDX4","DAZL","PIWIL1","SYCP3","PRM1","TNP1")
)