---
title: "Differential expression"
output: 
rmarkdown::html_vignette: 
toc: true
fig_width: 7 
fig_height: 8 
vignette: >
  %\VignetteIndexEntry{Differential expression}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
<style>
p.caption {
  font-size: 1.5em;
}
</style>
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## Introduction






## Very fast initial DE



``` {r fastDE}
##### CODE FROM WNV ANALYSIS TO BE REPURPOSED

enoughcells = names(which(table(clust) > 200))

ests11 = ps11 = ses11 = ests21 = ps21 = ses21 = beta0s = matrix(NA, ncol(norm), length(enoughcells),
                            dimnames = list(colnames(norm), enoughcells))

for (cell in enoughcells) {
  print(cell)
  # which genes to use:
  majorcell = map$Major_cell_type[map$Celltype_abb == cell]
  usegenes = rownames(iscontam)[!iscontam[, majorcell]]
  
  # get design matrix:
  inds = clust == cell
  templm = lm(norm[inds, 1] ~ annot$disease[inds] + niche[inds])
  X = model.matrix(templm)
  # get the estimates:
  beta <- solve(t(X) %*% X) %*% t(X) %*% norm[inds, usegenes]
  est11 <- beta[2, ]
  est21 <- beta[3, ]
  # get the SEs:
  resids <- norm[inds, usegenes] - X %*% beta
  rss <- colSums(resids^2)
  sigmasquared <- rss / (nrow(X) - ncol(X))
  se11 <- sqrt(solve(t(X) %*% X)[2,2] * sigmasquared)
  se21 <- sqrt(solve(t(X) %*% X)[3,3] * sigmasquared)
  # and the p-value:
  p11 <- 2 * (1 - pt(abs(est11) / se11, df = nrow(X) - ncol(X)))
  p21 <- 2 * (1 - pt(abs(est21) / se21, df = nrow(X) - ncol(X)))
  
  ests11[usegenes, cell] = est11
  ses11[usegenes, cell] = se11
  ps11[usegenes, cell] = p11
  ests21[usegenes, cell] = est21
  ses21[usegenes, cell] = se21
  ps21[usegenes, cell] = p21
  beta0s[usegenes, cell] = beta[1, ]
  
}

log2ratios11 = log2((beta0s + ests11) / beta0s)
log2ratios21 = log2((beta0s + ests21) / beta0s)

mat11 = log2ratios11 * (ps11 < 1e-4)
mat21 = log2ratios21 * (ps21 < 1e-4)
mat11 = replace(mat11, is.na(mat11), 0)
mat21 = replace(mat21, is.na(mat21), 0)

pdf("results/DE heatmaps - vs mock.pdf", height = 10)
pheatmap(mat11[rowSums(abs(mat11) > 1) > 2, ], main = "day 11 vs. mock", fontsize_row = 6,
         col = colorRampPalette(c("blue", "white", "red"))(100), breaks = seq(-2,2, length.out = 101))
pheatmap(mat21[rowSums(abs(mat21) > 1) > 2, ], main = "day 21 vs. mock", fontsize_row = 6,
         col = colorRampPalette(c("blue", "white", "red"))(100), breaks = seq(-2,2, length.out = 101))
dev.off()

```