project:
  type: book

book:
  title: "Vignette for CosMx analysis, updated for current best practices"
  author: "Patrick Danaher"
  date: last-modified
  date-format: medium

  # Chapters must be a properly indented list
  chapters:
    - index.qmd
    - 01-preprocessing.qmd

  # Book UI (books use a sidebar; navbar is for websites)
  sidebar:
    title: Some title
    logo: ./Images/logo_Bruker_black.png
    background: "#EBF0F2"
    # collapse-level controls how deep the sidebar auto-collapses
    collapse-level: 2

  # Offer downloads from the book
  downloads: [pdf, epub]

format:
  html:
    theme: custom.scss
    toc: true
    toc-expand: 2
    number-sections: true
    number-depth: 3
    code-fold: true
    code-summary: "Show the code"
    search: true            # search box in the header
    page-navigation: true   # next/prev links
    include-in-header:
      - text: |
          <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
          <script type="text/javascript">
            $(document).ready(function() {
              $('body').prepend('<div class="zoomDiv"><img src="" class="zoomImg"></div>');
              $('img:not(.zoomImg)').click(function() {
                $('.zoomImg').attr('src', $(this).attr('src')).css({width: '80%'});
                $('.zoomDiv').css({opacity: '1', width: 'auto', border: '1px solid white', borderRadius: '5px', position: 'fixed', top: '50%', left: '50%', marginRight: '-50%', transform: 'translate(-50%, -50%)', boxShadow: '0px 0px 50px #888888', zIndex: '50', overflow: 'auto', maxHeight: '100%'});
              });
              $('img.zoomImg').click(function() {
                $('.zoomDiv').css({opacity: '0', width: '0%'});
              });
            });
          </script>
  pdf:
    documentclass: scrreprt
    include-in-header:
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body:
      text: |
        \printindex
  epub:
    title: 'foobar'

editor:
  markdown:
    wrap: 72
