project:
  type: book

book:
  title: "Basic Analysis Vignette"
  chapters:
    - index.qmd        # optional landing page
    - 01_preprocessing.qmd
    - 02_exploratory_analysis.qmd
    - 03_DE.qmd

format:
  html:
    toc: true