// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// chunked_weighted_crossprod
Rcpp::List chunked_weighted_crossprod(const Eigen::MappedSparseMatrix<double>& X, Rcpp::NumericMatrix y_r, Rcpp::NumericVector w_r, int chunk_size);
RcppExport SEXP _HieraType_chunked_weighted_crossprod(SEXP XSEXP, SEXP y_rSEXP, SEXP w_rSEXP, SEXP chunk_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y_r(y_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type w_r(w_rSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_size(chunk_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(chunked_weighted_crossprod(X, y_r, w_r, chunk_size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HieraType_chunked_weighted_crossprod", (DL_FUNC) &_HieraType_chunked_weighted_crossprod, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_HieraType(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
