# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Chunked weighted cross-product for semi-dense sparse matrices
#'
#' Processes rows of X in dense chunks so each t(X)*X call hits BLAS dsyrk/dgemm,
#' avoiding CHOLMOD's sparse path that is slow at >10% density.
#' Peak memory is O(chunk_size * p) instead of O(N * p).
#'
#' @param X sparse N x p dgCMatrix (Xsigned assembled on the R side)
#' @param y_r dense N x m response matrix (double)
#' @param w_r prior_level_weights vector of length N, or length-0 numeric(0) for unweighted
#' @param chunk_size number of rows per BLAS chunk (default 10000)
#' @return named list: a = p x p (X'WX), b = p x m (X'Wy)
chunked_weighted_crossprod <- function(X, y_r, w_r, chunk_size = 10000L) {
    .Call('_HieraType_chunked_weighted_crossprod', PACKAGE = 'HieraType', X, y_r, w_r, chunk_size)
}

